# Generated by Django 3.2.16 on 2022-11-27 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dozent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Prof.', 'Prof.'), ('Dr.', 'Dr.')], default='Prof.', max_length=5)),
                ('vorname', models.CharField(max_length=50)),
                ('nachname', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Dozenten',
            },
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_name', models.CharField(max_length=50)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('ref_id', models.CharField(max_length=100)),
                ('ass_id', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('WS', 'Wintersemester'), ('SS', 'Sommersemester')], default='', max_length=3)),
                ('dozent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dozent')),
            ],
            options={
                'verbose_name_plural': 'Kurse',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('arbeitsstunden', models.FloatField(default=0)),
                ('tutor_id', models.CharField(max_length=30)),
                ('kurs_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kurs')),
            ],
            options={
                'verbose_name_plural': 'Tutoren',
            },
            bases=('core.user',),
            managers=[
                ('tutor', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_token', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kursleiter',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('kurs_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kurs')),
            ],
            options={
                'verbose_name_plural': 'Kursleiter',
            },
            bases=('core.user',),
            managers=[
                ('kursleiter', django.db.models.manager.Manager()),
            ],
        ),
    ]
